import Link from 'next/link'
import './globals.css'
import type { Metadata } from 'next'
import { Control } from './Control'


export const metadata: Metadata = {
  title: 'NextJS tutorial',
  description: 'Generated by create next app',
}


export default async function RootLayout({children}: {
  children: React.ReactNode
}) {

  // const res = await fetch('http://localhost:9999/topics',{cache:'no-cache'});
  // const topics = await res.json();

  const res = await fetch(`https://nextjs-git-main-chobkyu.vercel.app/api/items`,{cache:'no-cache'});
  //const res = await fetch(`http://localhost:3000/api/items`,{cache:'no-cache'});

  const topics = await res.json();

  const onclick = () => {
    console.log(res)
  }
  return (
    <html >
      <body>
        <h1><Link href='/'>WEB</Link></h1>
        <ol>
          {topics.data.map((topic:any) => {
            return <p key={topic.id}>{topic.userId}</p>
          })}
          {/* {topics.map((topic:any)=>{
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>

          })} */}
        </ol>
        {children}
        <Control/>
      </body>
    </html>
  )
}
